feat: update pre-commit prettier write issue

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -3,19 +3,14 @@
 set -eu
 
 run() {
-  echo "==> $*"
-  "$@"
+	echo "==> $*"
+	"$@"
 }
 
 run pnpm build
 run pnpm lint
 
-<<<<<<< HEAD
 if ! run pnpm prettier:check; then
-  echo "Prettier check failed. Run \`pnpm prettier:write\`, review the changes, stage them, and commit again."
-=======
-if ! git diff --quiet; then
-  echo "Prettier formatted files. Please review and stage the changes, then \`git add .\` and commit again"
->>>>>>> 850e054 (feat: add hint to the prettier)
-  exit 1
+	echo "Prettier check failed. Run \`pnpm prettier:write\`, review the changes, stage them, and commit again."
+	exit 1
 fi
